#!/bin/bash

if [ "$1" = "" ]; then
    echo "Give me at least OLD_USER_NAME!" >&2
    exit 1
elif [ "$1" = "-h" ]; then
    echo "git-fix-user OLD_USER_NAME [NEW_USER_NAME [NEW_USER_EMAIL]]"
    exit
fi

if [ "$2" = "" ]; then
    NEW_USER_NAME=$(git config user.name)
else
    NEW_USER_NAME=$2
fi

if [ "$3" = "" ]; then
    NEW_USER_EMAIL=$(git config user.email)
else
    NEW_USER_EMAIL=$3
fi

git filter-branch --commit-filter "
        if [ \"\$GIT_COMMITTER_NAME\" = \"$NEW_USER_NAME\" ];
        then
                GIT_COMMITTER_NAME=\"$NEW_USER_NAME\";
                GIT_AUTHOR_NAME=\"$NEW_USER_NAME\";
                GIT_COMMITTER_EMAIL=\"$NEW_USER_EMAIL\";
                GIT_AUTHOR_EMAIL=\"$NEW_USER_EMAIL\";
                git commit-tree \"\$@\";
        else
                git commit-tree \"\$@\";
        fi" HEAD
